In [1]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [2]:
train=pd.read_csv("ttrain.csv")

In [3]:
test=pd.read_csv("ttest.csv")

In [4]:
df=pd.concat([train, test], ignore_index=True)

In [5]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0.0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1.0,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1.0,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1.0,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0.0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1305,NaN,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
1305,1306,NaN,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
1306,1307,NaN,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
1307,1308,NaN,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
1308,1309,NaN,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1309 non-null   int64
 1   Survived     891 non-null    float64
 2   Pclass       1309 non-null   int64
 3   Name         1309 non-null   object
 4   Sex          1309 non-null   object
 5   Age          1046 non-null   float64
 6   SibSp        1309 non-null   int64
 7   Parch        1309 non-null   int64
 8   Ticket       1309 non-null   object
 9   Fare         1308 non-null   float64
 10  Cabin        295 non-null    object
 11  Embarked     1307 non-null   object
dtypes: float64(3), int64(4), object(5)
memory usage: 122.8+ KB

In [7]:
df.isnull().sum()

PassengerId       0
Survived        418
Pclass            0
Name              0
Sex               0
Age             263
SibSp             0
Parch             0
Ticket            0
Fare              1
Cabin          1014
Embarked          2
dtype: int64

In [8]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0.0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1.0,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1.0,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1.0,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0.0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1305,NaN,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
1305,1306,NaN,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
1306,1307,NaN,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
1307,1308,NaN,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
1308,1309,NaN,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [9]:
df.drop(["Ticket","PassengerId","Cabin"], axis=1, inplace=True)

In [10]:
df['Title'] = df['Name'].str.extract(r', (.*?)\.')[0]

In [11]:
df.drop("Name", axis=1, inplace=True)

In [12]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.linear_model import LinearRegression

In [13]:
columns_to_impute = ['Age', 'Fare']

imp = IterativeImputer(estimator=LinearRegression())
df[columns_to_impute] = imp.fit_transform(df[columns_to_impute])

In [14]:
df.isnull().sum()

Survived    418
Pclass        0
Sex           0
Age           0
SibSp         0
Parch         0
Fare          0
Embarked      2
Title         0
dtype: int64

In [15]:
df["Embarked"].fillna(df["Embarked"].mode()[0], inplace=True)

In [16]:
test = df[df['Survived'].isnull()]

In [17]:
train = df[df['Survived'].notnull()]

In [18]:
test

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Title
891,NaN,3,male,34.500000,0,0,7.8292,Q,Mr
892,NaN,3,female,47.000000,1,0,7.0000,S,Mrs
893,NaN,2,male,62.000000,0,0,9.6875,Q,Mr
894,NaN,3,male,27.000000,0,0,8.6625,S,Mr
895,NaN,3,female,22.000000,1,1,12.2875,S,Mrs
...,...,...,...,...,...,...,...,...,...
1304,NaN,3,male,28.553651,0,0,8.0500,S,Mr
1305,NaN,1,female,39.000000,0,0,108.9000,C,Dona
1306,NaN,3,male,38.500000,0,0,7.2500,S,Mr
1307,NaN,3,male,28.553651,0,0,8.0500,S,Mr
1308,NaN,3,male,29.216510,1,1,22.3583,C,Master

In [19]:
train=pd.get_dummies(train, drop_first=True)

In [20]:
from sklearn.preprocessing import MinMaxScaler

In [21]:
scaler = MinMaxScaler()
train = pd.DataFrame(scaler.fit_transform(train), columns=train.columns)

In [22]:
x=train.drop("Survived", axis=1)
y=train[["Survived"]]

In [23]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB

from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.metrics import f1_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split

b = BernoulliNB()
l = LogisticRegression()
d = DecisionTreeClassifier()
r = RandomForestClassifier()
gb= GradientBoostingClassifier()
kn= KNeighborsClassifier()
ab= AdaBoostClassifier()
mn= MultinomialNB()

def algo_test(x, y):
    modeller=[ b, l, d, r, gb, kn, ab, mn]
    isimler=["BernoulliNB", "LogisticRegression", "DecisionTreeClassifier", 
             "RandomForestClassifier", "GradientBoostingClassifier", "KNeighborsClassifier",
             "AdaBoostClassifier", "MultinomialNB"]

    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.3, random_state = 42)
    
    accuracy = []
    precision = []
    recall = []
    f1 = []
    mdl=[]

    print("Veriler hazır modeller deneniyor")
    for model in modeller:
        print(model, " modeli eğitiliyor!..")
        model=model.fit(x_train,y_train)
        tahmin=model.predict(x_test)
        mdl.append(model)
        accuracy.append(accuracy_score(y_test, tahmin))
        precision.append(precision_score(y_test, tahmin, average="micro"))
        recall.append(recall_score(y_test, tahmin, average="micro"))
        f1.append(f1_score(y_test, tahmin, average="micro"))
        print(confusion_matrix(y_test, tahmin))

    print("Eğitim tamamlandı.")
    
    metrics=pd.DataFrame(columns=["Accuracy", "Precision", "Recall", "F1", "Model"], index=isimler)
    metrics["Accuracy"] = accuracy
    metrics["Precision"] = precision  
    metrics["Recall"] = recall
    metrics["F1"] = f1
    metrics["Model"]=mdl

    metrics.sort_values("F1", ascending=False, inplace=True)

    print("En başarılı model: ", metrics.iloc[0].name)
    model=metrics.iloc[0,-1]
    tahmin=model.predict(np.array(x_test) if model==kn else x_test)
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, tahmin))
    print("classification Report:")
    print(classification_report(y_test, tahmin))
    print("Diğer Modeller:")
    
    return metrics.drop("Model", axis=1)

In [24]:
algo_test(x,y)

Veriler hazır modeller deneniyor
BernoulliNB()  modeli eğitiliyor!..
[[129  28]
 [ 27  84]]
LogisticRegression()  modeli eğitiliyor!..
[[134  23]
 [ 25  86]]
DecisionTreeClassifier()  modeli eğitiliyor!..
[[123  34]
 [ 31  80]]
RandomForestClassifier()  modeli eğitiliyor!..
[[132  25]
 [ 29  82]]
GradientBoostingClassifier()  modeli eğitiliyor!..
[[140  17]
 [ 34  77]]
KNeighborsClassifier()  modeli eğitiliyor!..
[[138  19]
 [ 34  77]]
AdaBoostClassifier()  modeli eğitiliyor!..
[[130  27]
 [ 28  83]]
MultinomialNB()  modeli eğitiliyor!..
[[134  23]
 [ 32  79]]
Eğitim tamamlandı.
En başarılı model:  LogisticRegression
Confusion Matrix:
[[134  23]
 [ 25  86]]
classification Report:
              precision    recall  f1-score   support

         0.0       0.84      0.85      0.85       157
         1.0       0.79      0.77      0.78       111

    accuracy                           0.82       268
   macro avg       0.82      0.81      0.81       268
weighted avg       0.82      0.82      0.82       268

Diğer Modeller:

                            Accuracy  Precision    Recall        F1
LogisticRegression          0.820896   0.820896  0.820896  0.820896
GradientBoostingClassifier  0.809701   0.809701  0.809701  0.809701
KNeighborsClassifier        0.802239   0.802239  0.802239  0.802239
RandomForestClassifier      0.798507   0.798507  0.798507  0.798507
BernoulliNB                 0.794776   0.794776  0.794776  0.794776
AdaBoostClassifier          0.794776   0.794776  0.794776  0.794776
MultinomialNB               0.794776   0.794776  0.794776  0.794776
DecisionTreeClassifier      0.757463   0.757463  0.757463  0.757463